### ISSUE TITLE
Please help! Your command made me crash my project for days!

### ISSUE THREAD

**Issue by BlackCorvuss** [ItzPike/DBM-Rawdata-Releases#12]
brother help please! I wanted to try this command and when executing it I send a strange error, close the program and when I open it again my project is not executed :(, I have implemented too many hours these days, please can you help me ??

**Comment by ItzPike** [comment]
Hi there!

I had taken a leave from the community for quite a while.
Sorry for the very very late response.
Please dm me on discord (Pike#0001) so I can further assist.
