### ISSUE TITLE
Reaction Role

### ISSUE THREAD

**Issue by Giveawaymania** [ItzPike/DBM-Rawdata-Releases#24]
After doing the first thing it asks saying to create a format, it always gives me the command "Prompt cancelled, you didnt provide a valid format with both required variables!"

Any help?

**Comment by ItzPike** [comment]
You can refer to the example but what it is asking here that you create a format how the emojis will be displayed.

For example, in that prompt you enter
**{emoji} -- {role}** then it would appear on each line **😀 -- ExampleRole** and so fourth

Example:
http://s1.webmshare.com/ojN40.webm
