### ISSUE TITLE
Bot doesnt give the role

### ISSUE THREAD

**Issue by florea326** [ItzPike/DBM-Rawdata-Releases#30]
Hi, the stup and all the things are as smooth as butter, but when I react to the message, it doesnt give the specified role, although i did the setup correctly. Can you Help?

**Comment by ItzPike** [comment]
You can contact me on Discord (Pike#0001) or message through here.
First, can you make sure that you have placed the event (reactionStart) in the events section of DBM?
Secondly, are you able to turn debug on and see if that outputs anything if you do react.

**Comment by ItzPike** [comment]
Closed; no response
