### ISSUE TITLE
TypeError: Cannot read property 'array' of undefined

### ISSUE THREAD

**Issue by taiten312** [ItzPike/DBM-Rawdata-Releases#34]
Hey, when I start up my bot and try to run your !rolemenu command I get this error here, It worked perfectly on another bot before and I don't know where this suddenly comes from, I would appreciate some advice, thanks! 

![image](https://user-images.githubusercontent.com/65783520/87499805-60686780-c65b-11ea-9918-e8c3bae8c96f.png)

**Comment by FoxXxHater** [comment]
Did you have correctly installed the mod files+ the actual version from discors.js and so on?

**Comment by taiten312** [comment]
Hey, I have tried your suggestion, it actually worked.
Thanks a lot.

**Comment by norilux** [comment]
Check your types bruh. Use TS
