### ISSUE TITLE
Reaction add/remove triggers stop working

### ISSUE THREAD

**Issue by ClementlaPizza** [ItzPike/DBM-Rawdata-Releases#36]
Hello, 
the choice of reactions work but only to remove a reaction but not the other way around. 
When I click on the emote it function 1x out of 20 that the role will give me, but when we uncheck the emote it is removed at all times.

Sorry for my english

**Comment by ItzPike** [comment]
This is a so far known issue and I exploring fixes. This may be due to Discord's new planned API changes and/or discord.js changes

**Comment by ClementlaPizza** [comment]
ok

**Comment by ItzPike** [comment]
As a temporary fix see if this can work

New event script (replace old with this one)
`const _this = this;
const fs = require('fs');

//Settings
const dmUserAfter = true; // Default, can be changed to false
var messageSentAdd = 'Successfully added the role {rolename} in {server}';
var messageSentRemove = 'Successfully removed the role {rolename} in {server}';
// The only variables that work rn, {rolename} and {server}


if(fs.existsSync('./data/reactionRoleData.json')) {
    fs.readFile('./data/reactionRoleData.json', function read(err, data) {
        if (err) {
            throw err;
        }
        data = JSON.parse(data)
    
        _this.storeValue(data, 3, 'reactionRoleInf', cache);
    });
} else {
    fs.writeFile("./data/reactionRoleData.json", "{}", function(err) {
        if(err) {
            return console.log(err);
        }
    });
    _this.storeValue({}, 3, 'reactionRoleInf', cache);
}

client.on('messageReactionAdd', async (reaction, user) => {
    if (!user.bot) {
        const reactionData = globalVars("reactionRoleInf");
        const reactionGuild = reaction.message.guild;
        const reactionMessage = reaction.message;
        if (reactionData.hasOwnProperty(reactionMessage.id)) {
            var emojiName = reaction.emoji.name;
            var roleInData = await reactionData[reactionMessage.id].filter(re => re[0] == emojiName || re[0].name == emojiName)
            if (roleInData.length != 0) {
                var guilduser = await reactionGuild.members.fetch(user.id);
                var roleData = roleInData[0][1];
                var reactionRole = await reactionGuild.roles.fetch(roleData);

                if (await guilduser.roles.cache.find(role => role.id == roleData) == null) {
                    guilduser.roles.add(reactionRole);

                    if (dmUserAfter) {
                        guilduser.send(messageSentAdd.replace("{rolename}", `**${reactionRole.name}**`).replace("{server}", `**${reactionGuild.name}**`));
                    }
                }
            }
        }
    }

});

client.on('messageReactionRemove', async (reaction, user)  => {
    if (!user.bot) {
        const reactionData = globalVars("reactionRoleInf");
        const reactionGuild = reaction.message.guild;
        const reactionMessage = reaction.message;
        if (reactionData.hasOwnProperty(reactionMessage.id)) {
            var emojiName = reaction.emoji.name;
            var roleInData = reactionData[reactionMessage.id].filter(re => re[0] == emojiName || re[0].name == emojiName)
            if (roleInData.length != 0) {
                var guilduser = await reactionGuild.members.fetch(user.id);
                var roleData = roleInData[0][1];
                var reactionRole = await reactionGuild.roles.fetch(roleData);

                if (guilduser.roles.cache.find(role => role.id == roleData) != null) {
                    guilduser.roles.remove(reactionRole);
                    if (dmUserAfter) {
                        guilduser.send(messageSentRemove.replace("{rolename}", `**${reactionRole.name}**`).replace("{server}", `**${reactionGuild.name}**`));
                    }
                }
            }
        }
    }
});`

Now locate your bot.js file and find this line
`Bot.initBot = function() {
    this.bot = new DiscordJS.Client();
};`

and replace it with 

`Bot.initBot = function() {
    this.bot = new DiscordJS.Client({partials: ['MESSAGE', 'CHANNEL', 'REACTION']});
};`

Now note this may interfere with some of your events cause what this does is enable the new v12 partial data. This means any data that gets casted to an event may be incomplete and could bug some things out. See if this work.

**Comment by YamaNizuke** [comment]
Hey! Work, is ok now! But after restart, rolemenu don't work anymore :<

**Comment by ItzPike** [comment]
This issue has been resolved in the latest version with a new note on how to fix this. Changes to bot.js can be reverted now as they are no longer needed. Sorry for the long time to fix this bug.

Fixed in: 0aae8486f0b4306354165a24f3c16c89bc50b634

**Comment by ItzPike** [comment]
Further instructions are found on the README.md file in the Role Reaction Folder.
