### ISSUE TITLE
RoleMenu after restart don't work + give but not remove roles

### ISSUE THREAD

**Issue by YamaNizuke** [ItzPike/DBM-Rawdata-Releases#37]
Hi,
I followed correctly the command, it worked perfectly but after a restart, the role menu reaction no longer work. (v12)

BONUS
When i put a rolemenu with my server emojis, give roles, but not remove them!
When i put a rolemenu with normal discord emoji, ex classic smile face etc., don't give roles, but remove them!

p.s. Sorry for my english / p.p.s. I am ✖ やまアパシー。め#6969

**Comment by ItzPike** [comment]
Duplicate of #36 
Further looking into this; will push out a fix hopefully today.
