### ISSUE TITLE
Love this but couple of issues

### ISSUE THREAD

**Issue by Lukemul6** [ItzPike/DBM-Rawdata-Releases#38]
When restarting the bot it does work any more, I get this error when trying to react after a restart - (error below)

Secondly, the role removal does not work. 

Not an issue but just wondering ->
Is there a way I could add a timed removal? For example I only want users to have the role for 15 minutes?

```(node:23316) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'bot' of undefined
    at eval (eval at Actions.eval (C:\Users\Luke\Desktop\Reaction\bot.js:344:10), <anonymous>:38:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:23316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23316) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by ItzPike** [comment]
Please provide the line above that for the full error. That allows me to better diagnose it.
Secondly, have you done the new steps that require you to enable intents?
With the timed removal, i'll have to see what I can do. That seems very situation specific and will not be used by many other people.

**Comment by ItzPike** [comment]
As a follow up, make sure you have updated to the latest version of the command

**Comment by ItzPike** [comment]
Closed due to lack of response
