### ISSUE TITLE
thumbnail

### ISSUE THREAD

**Issue by NiceATC** [ItzPike/DBM-Rawdata-Releases#40]
is possible add a thumbnail in final embed of giveaway?

**Comment by ItzPike** [comment]
I will see what I can do for that tho it should be pretty simple.
My stance is that it may generally over complicate the setup process for something that may be rarely used.
I may just release a version only here as a one off thing tho updates do muddy it up a bit.

**Comment by NiceATC** [comment]
I managed to put it on manually, thanks for the support

**Comment by NiceATC** [comment]
I didn't want to set up each new giveway, I just wanted to set a still image
