### ISSUE TITLE
Bot assigning wrong join invite on user join

### ISSUE THREAD

**Issue by DoggoModz** [ItzPike/DBM-Rawdata-Releases#43]
Using the invite manager thing. It keeps saying (user) invited (user) but the person who invited them and the inv link are both wrong. Its hard to explain but its using a inv link thats only had 2 invites but has said that person has invited them so far over 60 times
But the people joining are from a different invite link

**Comment by ItzPike** [comment]
Please contact me on Discord
Pike#6424

If you are able to contact me more about this.

**Comment by ItzPike** [comment]
Fixed in 483f30bdb9d28a314e9d0a08af3fb5b46f58884f
