### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by master3395** [ItzPike/DBM-Rawdata-Releases#7]
A way to do a "redraw" of the winner. If the winner, can't accept the price.
There should be a way to let another random user, in the reactions, win.

**Comment by ItzPike** [comment]
Sorry for the late response, and as I said the new re-write will allow the system to expand its functionalities. 

This of course, includes you being able to redraw the winner
I will be soon re-writing it.

As I told before, it can use a file system method.
Another method is through save variable and read file like the reaction role menu command.
The 2nd option may increase clutter in the cache but be somewhat easier to setup.

I am still, planning this out.
Any updates I will post on the trello page.
https://trello.com/b/LdME9NTm/current-projects-discord-bot
