### ISSUE TITLE
Suggestion/Question

### ISSUE THREAD

**Issue by master3395** [ItzPike/DBM-Rawdata-Releases#8]
Is there a way to store the giveaway information, if the bot restarts.
So it continues?

**Comment by ItzPike** [comment]
Sorry for the late response, but anyways I am looking into this.
I am planning for a re-write soon of the giveaway but I am not sure when.
This will of course include a different way to end the giveaway that works after restart.

What I have planned is a file system where it will read and compare time in the file to end the giveaway if said time already passed

Some failsafes will be built in to delete the file for giveaways that are deleted
This system also allows a giveaway end.

This will hopefully be coming soon in the future

Any updates will be here on the trello page.
https://trello.com/b/LdME9NTm/current-projects-discord-bot

**Comment by master3395** [comment]
Awesome, i am looking forward for the planned boards :)
Good work.
